package linear_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/bruin-data/ingestr/internal/testutil"
	"github.com/bruin-data/ingestr/pkg/schema"
)

func TestLinearPipeline(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	key := os.Getenv("LINEAR_API_KEY")
	if key == "" {
		t.Skip("Set LINEAR_API_KEY to run Linear integration tests")
	}

	ctx := context.Background()
	sourceURI := fmt.Sprintf("linear://?api_key=%s", key)

	tmpDir := t.TempDir()
	dbPath := filepath.Join(tmpDir, fmt.Sprintf("linear_%d.duckdb", time.Now().UnixNano()))
	destURI := fmt.Sprintf("duckdb:///%s", dbPath)

	expectations := []testutil.TableExpectation{
		{
			SourceTable: "organization",
			DestTable:   "main.linear_organization",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "name", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "allowedAuthServices", DataType: schema.TypeJSON},
				{Name: "createdIssueCount", DataType: schema.TypeInt64},
				{Name: "customerCount", DataType: schema.TypeInt64},
				{Name: "customersEnabled", DataType: schema.TypeBoolean},
				{Name: "gitLinkbackMessagesEnabled", DataType: schema.TypeBoolean},
				{Name: "gitPublicLinkbackMessagesEnabled", DataType: schema.TypeBoolean},
				{Name: "periodUploadVolume", DataType: schema.TypeFloat64},
				{Name: "previousUrlKeys", DataType: schema.TypeJSON},
				{Name: "roadmapEnabled", DataType: schema.TypeBoolean},
				{Name: "samlEnabled", DataType: schema.TypeBoolean},
				{Name: "scimEnabled", DataType: schema.TypeBoolean},
			},
			ExpectedRowCount: 1,
			Rows: []testutil.ExpectedRow{
				{
					ID: "a8069e06-708f-4494-95d1-bd4f4be776c4",
					Fields: map[string]any{
						"name":                             "Gong Integration Test",
						"createdAt":                        time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"updatedAt":                        time.Date(2026, 2, 13, 13, 21, 59, 844000000, time.UTC),
						"createdIssueCount":                int64(5),
						"customerCount":                    int64(0),
						"customersEnabled":                 false,
						"gitLinkbackMessagesEnabled":       true,
						"gitPublicLinkbackMessagesEnabled": false,
						"periodUploadVolume":               float64(0),
						"roadmapEnabled":                   false,
						"samlEnabled":                      false,
						"scimEnabled":                      false,
					},
				},
			},
		},
		{
			SourceTable: "issue_labels",
			DestTable:   "main.linear_issue_labels",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "color", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "name", DataType: schema.TypeString},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "creatorId", DataType: schema.TypeString},
				{Name: "organizationId", DataType: schema.TypeString},
			},
			ExpectedRowCount: 4,
			Rows: []testutil.ExpectedRow{
				{
					ID: "e73034c5-4fdc-45f8-8d2a-1067a7739a79",
					Fields: map[string]any{
						"color":          "#4cb782",
						"createdAt":      time.Date(2026, 2, 13, 10, 21, 28, 908000000, time.UTC),
						"name":           "gong-test",
						"updatedAt":      time.Date(2026, 2, 13, 10, 21, 28, 908000000, time.UTC),
						"creatorId":      "45e89c07-63ee-418d-9dca-7ca9f06840d5",
						"organizationId": "a8069e06-708f-4494-95d1-bd4f4be776c4",
					},
				},
				{
					ID: "19d962d3-977c-406d-82ea-743c78588383",
					Fields: map[string]any{
						"color":          "#EB5757",
						"createdAt":      time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":           "Bug",
						"updatedAt":      time.Date(2026, 2, 13, 10, 21, 38, 582000000, time.UTC),
						"creatorId":      nil,
						"organizationId": "a8069e06-708f-4494-95d1-bd4f4be776c4",
					},
				},
				{
					ID: "65e126a1-609d-4ce7-b325-ddbe197db5ee",
					Fields: map[string]any{
						"color":          "#BB87FC",
						"createdAt":      time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":           "Feature",
						"updatedAt":      time.Date(2026, 2, 13, 13, 20, 45, 714000000, time.UTC),
						"creatorId":      nil,
						"organizationId": "a8069e06-708f-4494-95d1-bd4f4be776c4",
					},
				},
				{
					ID: "2d1d1b01-cf3a-455b-a0ba-ff6dc4414e43",
					Fields: map[string]any{
						"color":          "#4EA7FC",
						"createdAt":      time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":           "Improvement",
						"updatedAt":      time.Date(2026, 2, 13, 13, 21, 10, 913000000, time.UTC),
						"creatorId":      nil,
						"organizationId": "a8069e06-708f-4494-95d1-bd4f4be776c4",
					},
				},
			},
		},
		{
			SourceTable: "teams",
			DestTable:   "main.linear_teams",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "name", DataType: schema.TypeString},
				{Name: "key", DataType: schema.TypeString},
				{Name: "color", DataType: schema.TypeString},
				{Name: "icon", DataType: schema.TypeString},
				{Name: "private", DataType: schema.TypeBoolean},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "organizationId", DataType: schema.TypeString},
				{Name: "cyclesEnabled", DataType: schema.TypeBoolean},
				{Name: "cycleDuration", DataType: schema.TypeFloat64},
				{Name: "cycleStartDay", DataType: schema.TypeFloat64},
				{Name: "cycleCooldownTime", DataType: schema.TypeFloat64},
				{Name: "issueCount", DataType: schema.TypeInt64},
				{Name: "issueEstimationType", DataType: schema.TypeString},
				{Name: "issueEstimationAllowZero", DataType: schema.TypeBoolean},
				{Name: "issueEstimationExtended", DataType: schema.TypeBoolean},
				{Name: "issueOrderingNoPriorityFirst", DataType: schema.TypeBoolean},
				{Name: "autoArchivePeriod", DataType: schema.TypeFloat64},
				{Name: "autoClosePeriod", DataType: schema.TypeFloat64},
				{Name: "groupIssueHistory", DataType: schema.TypeBoolean},
				{Name: "timezone", DataType: schema.TypeString},
				{Name: "inviteHash", DataType: schema.TypeString},
				{Name: "slackNewIssue", DataType: schema.TypeBoolean},
				{Name: "slackIssueComments", DataType: schema.TypeBoolean},
				{Name: "slackIssueStatuses", DataType: schema.TypeBoolean},
				{Name: "triageEnabled", DataType: schema.TypeBoolean},
				{Name: "requirePriorityToLeaveTriage", DataType: schema.TypeBoolean},
				{Name: "upcomingCycleCount", DataType: schema.TypeFloat64},
			},
			ExpectedRowCount: 1,
			Rows: []testutil.ExpectedRow{
				{
					ID: "81528680-dc3f-4a1a-9525-ae9a66d780c3",
					Fields: map[string]any{
						"name":                         "Gong Integration Test",
						"key":                          "GON",
						"color":                        "#9577ff",
						"icon":                         "Favorite",
						"private":                      false,
						"createdAt":                    time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"updatedAt":                    time.Date(2026, 2, 13, 12, 34, 6, 870000000, time.UTC),
						"organizationId":               "a8069e06-708f-4494-95d1-bd4f4be776c4",
						"cyclesEnabled":                false,
						"cycleDuration":                float64(2),
						"cycleStartDay":                float64(1),
						"cycleCooldownTime":            float64(0),
						"issueCount":                   int64(5),
						"issueEstimationType":          "notUsed",
						"issueEstimationAllowZero":     false,
						"issueEstimationExtended":      false,
						"issueOrderingNoPriorityFirst": false,
						"autoArchivePeriod":            float64(6),
						"autoClosePeriod":              float64(6),
						"groupIssueHistory":            true,
						"timezone":                     "Europe/Istanbul",
						"inviteHash":                   "",
						"slackNewIssue":                true,
						"slackIssueComments":           true,
						"slackIssueStatuses":           true,
						"triageEnabled":                false,
						"requirePriorityToLeaveTriage": false,
						"upcomingCycleCount":           float64(2),
					},
				},
			},
		},
		{
			SourceTable: "workflow_states",
			DestTable:   "main.linear_workflow_states",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "color", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "name", DataType: schema.TypeString},
				{Name: "position", DataType: schema.TypeFloat64},
				{Name: "type", DataType: schema.TypeString},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
			},
			ExpectedRowCount: 6,
			Rows: []testutil.ExpectedRow{
				{
					ID: "8f98b286-3a14-4768-be54-d2711b15c5c6",
					Fields: map[string]any{
						"color":     "#bec2c8",
						"createdAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":      "Backlog",
						"position":  float64(0.0),
						"type":      "backlog",
						"updatedAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "7d53a4b7-d6c3-4c6b-b2ff-76551c3dc5d9",
					Fields: map[string]any{
						"color":     "#95a2b3",
						"createdAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":      "Duplicate",
						"position":  float64(5.0),
						"type":      "canceled",
						"updatedAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "58c040c6-784b-42b3-863a-f7ac071f2378",
					Fields: map[string]any{
						"color":     "#e2e2e2",
						"createdAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":      "Todo",
						"position":  float64(1.0),
						"type":      "unstarted",
						"updatedAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "17e188dc-4004-4b7f-afa9-279abfe2ba45",
					Fields: map[string]any{
						"color":     "#f2c94c",
						"createdAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":      "In Progress",
						"position":  float64(2.0),
						"type":      "started",
						"updatedAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "0ca6fc96-701b-43a6-abd2-fd0b23142438",
					Fields: map[string]any{
						"color":     "#5e6ad2",
						"createdAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":      "Done",
						"position":  float64(3.0),
						"type":      "completed",
						"updatedAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "06aae540-0a31-4f32-b02c-71f16362b12f",
					Fields: map[string]any{
						"color":     "#95a2b3",
						"createdAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"name":      "Canceled",
						"position":  float64(4.0),
						"type":      "canceled",
						"updatedAt": time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
			},
		},
		{
			SourceTable: "project_statuses",
			DestTable:   "main.linear_project_statuses",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "archivedAt", DataType: schema.TypeTimestampTZ},
				{Name: "color", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "description", DataType: schema.TypeString},
				{Name: "indefinite", DataType: schema.TypeBoolean},
				{Name: "name", DataType: schema.TypeString},
				{Name: "position", DataType: schema.TypeFloat64},
				{Name: "type", DataType: schema.TypeString},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
			},
			ExpectedRowCount: 5,
			Rows: []testutil.ExpectedRow{
				{
					ID: "cb5ee008-d401-4c63-8dfe-2aa3616ee875",
					Fields: map[string]any{
						"archivedAt":  nil,
						"color":       "#D7D8DB",
						"createdAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"description": nil,
						"indefinite":  false,
						"name":        "Planned",
						"position":    float64(1),
						"type":        "planned",
						"updatedAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "9f8831cc-6324-439e-bccf-92e5d26f4628",
					Fields: map[string]any{
						"archivedAt":  nil,
						"color":       "#5E6AD2",
						"createdAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"description": nil,
						"indefinite":  false,
						"name":        "Completed",
						"position":    float64(3),
						"type":        "completed",
						"updatedAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "949fc62c-258c-4003-a963-5d265fcadf3e",
					Fields: map[string]any{
						"archivedAt":  nil,
						"color":       "#8A8F98",
						"createdAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"description": nil,
						"indefinite":  false,
						"name":        "Canceled",
						"position":    float64(4),
						"type":        "canceled",
						"updatedAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "57e8865f-dddc-48e3-ae8d-7de0b659fc87",
					Fields: map[string]any{
						"archivedAt":  nil,
						"color":       "#F2C94C",
						"createdAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"description": nil,
						"indefinite":  false,
						"name":        "In Progress",
						"position":    float64(2),
						"type":        "started",
						"updatedAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
				{
					ID: "03c87edc-038f-4801-9d7d-f22255a5ee2e",
					Fields: map[string]any{
						"archivedAt":  nil,
						"color":       "#F2994A",
						"createdAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"description": nil,
						"indefinite":  false,
						"name":        "Backlog",
						"position":    float64(0),
						"type":        "backlog",
						"updatedAt":   time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
					},
				},
			},
		},
		{
			SourceTable: "users",
			DestTable:   "main.linear_users",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "active", DataType: schema.TypeBoolean},
				{Name: "admin", DataType: schema.TypeBoolean},
				{Name: "archivedAt", DataType: schema.TypeTimestampTZ},
				{Name: "avatarUrl", DataType: schema.TypeString},
				{Name: "calendarHash", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "createdIssueCount", DataType: schema.TypeInt64},
				{Name: "description", DataType: schema.TypeString},
				{Name: "disableReason", DataType: schema.TypeString},
				{Name: "displayName", DataType: schema.TypeString},
				{Name: "email", DataType: schema.TypeString},
				{Name: "guest", DataType: schema.TypeBoolean},
				{Name: "inviteHash", DataType: schema.TypeString},
				{Name: "lastSeen", DataType: schema.TypeTimestampTZ},
				{Name: "name", DataType: schema.TypeString},
				{Name: "statusEmoji", DataType: schema.TypeString},
				{Name: "statusLabel", DataType: schema.TypeString},
				{Name: "statusUntilAt", DataType: schema.TypeTimestampTZ},
				{Name: "timezone", DataType: schema.TypeString},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "url", DataType: schema.TypeString},
				{Name: "organizationId", DataType: schema.TypeString},
			},
			ExpectedRowCount: 1,
			Rows: []testutil.ExpectedRow{
				{
					ID: "45e89c07-63ee-418d-9dca-7ca9f06840d5",
					Fields: map[string]any{
						"active":            true,
						"admin":             true,
						"archivedAt":        nil,
						"avatarUrl":         nil,
						"calendarHash":      nil,
						"createdAt":         time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"createdIssueCount": int64(1),
						"description":       nil,
						"disableReason":     nil,
						"displayName":       "vendor_accounts",
						"email":             "vendor_accounts@getbruin.com",
						"guest":             false,
						"inviteHash":        "",
						"name":              "vendor_accounts@getbruin.com",
						"statusEmoji":       nil,
						"statusLabel":       nil,
						"statusUntilAt":     nil,
						"timezone":          "Europe/Istanbul",
						"updatedAt":         time.Date(2026, 2, 13, 10, 8, 0, 142000000, time.UTC),
						"url":               "https://linear.app/gong-integration-test/profiles/vendor_accounts",
						"organizationId":    "a8069e06-708f-4494-95d1-bd4f4be776c4",
					},
				},
			},
		},
		{
			SourceTable: "issues",
			DestTable:   "main.linear_issues",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "title", DataType: schema.TypeString},
				{Name: "description", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "archivedAt", DataType: schema.TypeTimestampTZ},
				{Name: "addedToCycleAt", DataType: schema.TypeTimestampTZ},
				{Name: "autoArchivedAt", DataType: schema.TypeTimestampTZ},
				{Name: "autoClosedAt", DataType: schema.TypeTimestampTZ},
				{Name: "boardOrder", DataType: schema.TypeFloat64},
				{Name: "branchName", DataType: schema.TypeString},
				{Name: "canceledAt", DataType: schema.TypeTimestampTZ},
				{Name: "completedAt", DataType: schema.TypeTimestampTZ},
				{Name: "customerTicketCount", DataType: schema.TypeInt64},
				{Name: "descriptionState", DataType: schema.TypeString},
				{Name: "dueDate", DataType: schema.TypeString},
				{Name: "estimate", DataType: schema.TypeFloat64},
				{Name: "identifier", DataType: schema.TypeString},
				{Name: "integrationSourceType", DataType: schema.TypeString},
				{Name: "labelIds", DataType: schema.TypeJSON},
				{Name: "number", DataType: schema.TypeFloat64},
				{Name: "previousIdentifiers", DataType: schema.TypeJSON},
				{Name: "priority", DataType: schema.TypeFloat64},
				{Name: "priorityLabel", DataType: schema.TypeString},
				{Name: "prioritySortOrder", DataType: schema.TypeFloat64},
				{Name: "reactionData", DataType: schema.TypeJSON},
				{Name: "slaBreachesAt", DataType: schema.TypeTimestampTZ},
				{Name: "slaHighRiskAt", DataType: schema.TypeTimestampTZ},
				{Name: "slaMediumRiskAt", DataType: schema.TypeTimestampTZ},
				{Name: "slaStartedAt", DataType: schema.TypeTimestampTZ},
				{Name: "slaType", DataType: schema.TypeString},
				{Name: "snoozedUntilAt", DataType: schema.TypeTimestampTZ},
				{Name: "sortOrder", DataType: schema.TypeFloat64},
				{Name: "startedAt", DataType: schema.TypeTimestampTZ},
				{Name: "startedTriageAt", DataType: schema.TypeTimestampTZ},
				{Name: "subIssueSortOrder", DataType: schema.TypeFloat64},
				{Name: "triagedAt", DataType: schema.TypeTimestampTZ},
				{Name: "url", DataType: schema.TypeString},
				{Name: "creatorId", DataType: schema.TypeString},
				{Name: "assigneeId", DataType: schema.TypeString},
				{Name: "botActor", DataType: schema.TypeJSON},
				{Name: "cycleId", DataType: schema.TypeString},
				{Name: "delegateId", DataType: schema.TypeString},
				{Name: "externalUserCreatorId", DataType: schema.TypeString},
				{Name: "favoriteId", DataType: schema.TypeString},
				{Name: "lastAppliedTemplateId", DataType: schema.TypeString},
				{Name: "parentId", DataType: schema.TypeString},
				{Name: "projectMilestoneId", DataType: schema.TypeString},
				{Name: "recurringIssueTemplateId", DataType: schema.TypeString},
				{Name: "snoozedById", DataType: schema.TypeString},
				{Name: "sourceCommentId", DataType: schema.TypeString},
				{Name: "stateId", DataType: schema.TypeString},
				{Name: "labels", DataType: schema.TypeJSON},
			},
			ExpectedRowCount: 5,
			Rows: []testutil.ExpectedRow{
				{
					ID: "650b87fc-3d98-407d-b5d5-d50ce94e3b42",
					Fields: map[string]any{
						"title":                    "Test issue for gong integration",
						"description":              "This is a test issue created for gong integration testing",
						"createdAt":                time.Date(2026, 2, 13, 10, 21, 31, 813000000, time.UTC),
						"updatedAt":                time.Date(2026, 2, 13, 13, 20, 45, 549000000, time.UTC),
						"archivedAt":               nil,
						"addedToCycleAt":           nil,
						"autoArchivedAt":           nil,
						"autoClosedAt":             nil,
						"boardOrder":               float64(0),
						"branchName":               "vendor-accounts/gon-5-test-issue-for-gong-integration",
						"canceledAt":               nil,
						"completedAt":              nil,
						"customerTicketCount":      int64(0),
						"dueDate":                  nil,
						"estimate":                 nil,
						"identifier":               "GON-5",
						"integrationSourceType":    nil,
						"number":                   float64(5),
						"priority":                 float64(2),
						"priorityLabel":            "High",
						"prioritySortOrder":        float64(-4256.0),
						"slaBreachesAt":            nil,
						"slaHighRiskAt":            nil,
						"slaMediumRiskAt":          nil,
						"slaStartedAt":             nil,
						"slaType":                  "all",
						"snoozedUntilAt":           nil,
						"sortOrder":                float64(-50.0),
						"startedAt":                time.Date(2026, 2, 13, 10, 21, 31, 860000000, time.UTC),
						"startedTriageAt":          nil,
						"subIssueSortOrder":        nil,
						"triagedAt":                nil,
						"url":                      "https://linear.app/gong-integration-test/issue/GON-5/test-issue-for-gong-integration",
						"creatorId":                "45e89c07-63ee-418d-9dca-7ca9f06840d5",
						"assigneeId":               "45e89c07-63ee-418d-9dca-7ca9f06840d5",
						"cycleId":                  nil,
						"delegateId":               nil,
						"externalUserCreatorId":    nil,
						"favoriteId":               nil,
						"lastAppliedTemplateId":    nil,
						"parentId":                 nil,
						"projectMilestoneId":       nil,
						"recurringIssueTemplateId": nil,
						"snoozedById":              nil,
						"sourceCommentId":          nil,
						"stateId":                  "17e188dc-4004-4b7f-afa9-279abfe2ba45",
					},
				},
				{
					ID: "8fa4c9ff-9d68-41b5-90b7-36f2d7b590bc",
					Fields: map[string]any{
						"title":                    "Get familiar with Linear",
						"createdAt":                time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"updatedAt":                time.Date(2026, 2, 13, 13, 21, 10, 725000000, time.UTC),
						"archivedAt":               nil,
						"addedToCycleAt":           nil,
						"autoArchivedAt":           nil,
						"autoClosedAt":             nil,
						"boardOrder":               float64(0),
						"branchName":               "vendor-accounts/gon-1-get-familiar-with-linear",
						"canceledAt":               nil,
						"completedAt":              time.Date(2026, 2, 13, 10, 21, 34, 370000000, time.UTC),
						"customerTicketCount":      int64(0),
						"dueDate":                  nil,
						"estimate":                 nil,
						"identifier":               "GON-1",
						"integrationSourceType":    nil,
						"number":                   float64(1),
						"priority":                 float64(0),
						"priorityLabel":            "No priority",
						"prioritySortOrder":        float64(0.0),
						"slaBreachesAt":            nil,
						"slaHighRiskAt":            nil,
						"slaMediumRiskAt":          nil,
						"slaStartedAt":             nil,
						"slaType":                  "all",
						"snoozedUntilAt":           nil,
						"sortOrder":                float64(54.0),
						"startedAt":                nil,
						"startedTriageAt":          nil,
						"subIssueSortOrder":        nil,
						"triagedAt":                nil,
						"url":                      "https://linear.app/gong-integration-test/issue/GON-1/get-familiar-with-linear",
						"creatorId":                nil,
						"assigneeId":               "45e89c07-63ee-418d-9dca-7ca9f06840d5",
						"cycleId":                  nil,
						"delegateId":               nil,
						"externalUserCreatorId":    nil,
						"favoriteId":               nil,
						"lastAppliedTemplateId":    nil,
						"parentId":                 nil,
						"projectMilestoneId":       nil,
						"recurringIssueTemplateId": nil,
						"snoozedById":              nil,
						"sourceCommentId":          nil,
						"stateId":                  "0ca6fc96-701b-43a6-abd2-fd0b23142438",
					},
				},
			},
		},
		{
			SourceTable: "projects",
			DestTable:   "main.linear_projects",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "name", DataType: schema.TypeString},
				{Name: "description", DataType: schema.TypeString},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "archivedAt", DataType: schema.TypeTimestampTZ},
				{Name: "completedAt", DataType: schema.TypeTimestampTZ},
				{Name: "canceledAt", DataType: schema.TypeTimestampTZ},
				{Name: "startedAt", DataType: schema.TypeTimestampTZ},
				{Name: "color", DataType: schema.TypeString},
				{Name: "icon", DataType: schema.TypeString},
				{Name: "slugId", DataType: schema.TypeString},
				{Name: "url", DataType: schema.TypeString},
				{Name: "health", DataType: schema.TypeString},
				{Name: "priority", DataType: schema.TypeInt64},
				{Name: "priorityLabel", DataType: schema.TypeString},
				{Name: "state", DataType: schema.TypeString},
				{Name: "targetDate", DataType: schema.TypeString},
				{Name: "startDate", DataType: schema.TypeString},
				{Name: "progress", DataType: schema.TypeFloat64},
				{Name: "currentProgress", DataType: schema.TypeJSON},
				{Name: "scope", DataType: schema.TypeFloat64},
				{Name: "sortOrder", DataType: schema.TypeFloat64},
				{Name: "trashed", DataType: schema.TypeBoolean},
				{Name: "creatorId", DataType: schema.TypeString},
				{Name: "leadId", DataType: schema.TypeString},
			},
			ExpectedRowCount: 1,
			Rows: []testutil.ExpectedRow{
				{
					ID: "16b2a1f7-e5dd-4138-b8e5-0a6f9978e545",
					Fields: map[string]any{
						"name":          "Gong Test",
						"description":   "",
						"createdAt":     time.Date(2026, 2, 13, 13, 21, 59, 778000000, time.UTC),
						"updatedAt":     time.Date(2026, 2, 13, 13, 21, 59, 778000000, time.UTC),
						"archivedAt":    nil,
						"completedAt":   nil,
						"canceledAt":    nil,
						"startedAt":     nil,
						"color":         "#bec2c8",
						"icon":          nil,
						"slugId":        "889a3e06bee8",
						"url":           "https://linear.app/gong-integration-test/project/gong-test-889a3e06bee8",
						"health":        nil,
						"priority":      int64(0),
						"priorityLabel": "No priority",
						"state":         "backlog",
						"targetDate":    "2026-02-19",
						"startDate":     "2026-02-17",
						"progress":      float64(0.0),
						"scope":         float64(0),
						"sortOrder":     float64(79.36),
						"trashed":       nil,
						"creatorId":     "45e89c07-63ee-418d-9dca-7ca9f06840d5",
						"leadId":        "45e89c07-63ee-418d-9dca-7ca9f06840d5",
					},
				},
			},
		},
		{
			SourceTable: "team_memberships",
			DestTable:   "main.linear_team_memberships",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "archivedAt", DataType: schema.TypeTimestampTZ},
				{Name: "createdAt", DataType: schema.TypeTimestampTZ},
				{Name: "owner", DataType: schema.TypeBoolean},
				{Name: "sortOrder", DataType: schema.TypeFloat64},
				{Name: "updatedAt", DataType: schema.TypeTimestampTZ},
				{Name: "userId", DataType: schema.TypeString},
			},
			ExpectedRowCount: 1,
			Rows: []testutil.ExpectedRow{
				{
					ID: "562e041c-0023-49cd-95d7-d8f5cfb3fb21",
					Fields: map[string]any{
						"archivedAt": nil,
						"createdAt":  time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"owner":      false,
						"sortOrder":  float64(94.0),
						"updatedAt":  time.Date(2026, 2, 13, 10, 7, 56, 324000000, time.UTC),
						"userId":     "45e89c07-63ee-418d-9dca-7ca9f06840d5",
					},
				},
			},
		},
	}

	for _, exp := range expectations {
		t.Run(exp.SourceTable, func(t *testing.T) {
			testutil.RunPipeline(t, ctx, sourceURI, destURI, exp)
			testutil.Check(t, destURI, exp)
		})
	}
}
