package docebo

import (
	"github.com/bruin-data/gong/pkg/schema"
)

type ResourceConfig struct {
	Endpoint string
	Columns  []schema.Column
}

var doceboResources = map[string]ResourceConfig{
	"users": {
		Endpoint: "users",
		Columns: []schema.Column{
			{Name: "user_id", DataType: schema.TypeString, Nullable: true},
			{Name: "username", DataType: schema.TypeString, Nullable: true},
			{Name: "first_name", DataType: schema.TypeString, Nullable: true},
			{Name: "last_name", DataType: schema.TypeString, Nullable: true},
			{Name: "email", DataType: schema.TypeString, Nullable: true},
			{Name: "uuid", DataType: schema.TypeString, Nullable: true},
			{Name: "is_manager", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "fullname", DataType: schema.TypeString, Nullable: true},
			{Name: "last_access_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "last_update", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "creation_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "status", DataType: schema.TypeString, Nullable: true},
			{Name: "avatar", DataType: schema.TypeString, Nullable: true},
			{Name: "language", DataType: schema.TypeString, Nullable: true},
			{Name: "lang_code", DataType: schema.TypeString, Nullable: true},
			{Name: "level", DataType: schema.TypeString, Nullable: true},
			{Name: "email_validation_status", DataType: schema.TypeString, Nullable: true},
			{Name: "send_notification", DataType: schema.TypeString, Nullable: true},
			{Name: "newsletter_optout", DataType: schema.TypeString, Nullable: true},
			{Name: "encoded_username", DataType: schema.TypeString, Nullable: true},
			{Name: "timezone", DataType: schema.TypeString, Nullable: true},
			{Name: "active_subordinates_count", DataType: schema.TypeInt64, Nullable: true},
			{Name: "expired", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "multidomains", DataType: schema.TypeJSON, Nullable: true},
			{Name: "manager_names", DataType: schema.TypeJSON, Nullable: true},
			{Name: "managers", DataType: schema.TypeJSON, Nullable: true},
			{Name: "actions", DataType: schema.TypeJSON, Nullable: true},
		},
	},
	"courses": {
		Endpoint: "courses",
		Columns: []schema.Column{
			{Name: "id_course", DataType: schema.TypeInt64, Nullable: true},
			{Name: "name", DataType: schema.TypeString, Nullable: true},
			{Name: "uidCourse", DataType: schema.TypeString, Nullable: true},
			{Name: "description", DataType: schema.TypeString, Nullable: true},
			{Name: "date_last_updated", DataType: schema.TypeDate, Nullable: true},
			{Name: "course_type", DataType: schema.TypeString, Nullable: true},
			{Name: "selling", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "code", DataType: schema.TypeString, Nullable: true},
			{Name: "slug_name", DataType: schema.TypeString, Nullable: true},
			{Name: "image", DataType: schema.TypeString, Nullable: true},
			{Name: "duration", DataType: schema.TypeInt64, Nullable: true},
			{Name: "language", DataType: schema.TypeString, Nullable: true},
			{Name: "language_label", DataType: schema.TypeString, Nullable: true},
			{Name: "multi_languages", DataType: schema.TypeJSON, Nullable: true},
			{Name: "price", DataType: schema.TypeString, Nullable: true},
			{Name: "is_new", DataType: schema.TypeString, Nullable: true},
			{Name: "is_opened", DataType: schema.TypeString, Nullable: true},
			{Name: "rating_option", DataType: schema.TypeString, Nullable: true},
			{Name: "current_rating", DataType: schema.TypeInt64, Nullable: true},
			{Name: "credits", DataType: schema.TypeInt64, Nullable: true},
			{Name: "img_url", DataType: schema.TypeString, Nullable: true},
			{Name: "can_rate", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "can_self_unenroll", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "start_date", DataType: schema.TypeDate, Nullable: true},
			{Name: "end_date", DataType: schema.TypeDate, Nullable: true},
			{Name: "category", DataType: schema.TypeJSON, Nullable: true},
			{Name: "enrollment_policy", DataType: schema.TypeInt64, Nullable: true},
			{Name: "max_attempts", DataType: schema.TypeInt64, Nullable: true},
			{Name: "available_seats", DataType: schema.TypeJSON, Nullable: true},
			{Name: "is_affiliate", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "partner_fields", DataType: schema.TypeString, Nullable: true},
			{Name: "partner_data", DataType: schema.TypeJSON, Nullable: true},
			{Name: "affiliate_price", DataType: schema.TypeString, Nullable: true},
		},
	},
	"user_fields": {
		Endpoint: "user_fields",
		Columns: []schema.Column{
			{Name: "id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "name", DataType: schema.TypeString, Nullable: true},
			{Name: "type", DataType: schema.TypeString, Nullable: true},
			{Name: "mandatory", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "show_on_detail", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "show_in_filter", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "options", DataType: schema.TypeJSON, Nullable: true},
			{Name: "ref_area", DataType: schema.TypeInt64, Nullable: true},
			{Name: "is_valid", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "sequence", DataType: schema.TypeInt64, Nullable: true},
		},
	},
	"branches": {
		Endpoint: "branches",
		Columns: []schema.Column{
			{Name: "id_org", DataType: schema.TypeInt64, Nullable: true},
			{Name: "id_parent", DataType: schema.TypeInt64, Nullable: true},
			{Name: "lft", DataType: schema.TypeInt64, Nullable: true},
			{Name: "rgt", DataType: schema.TypeInt64, Nullable: true},
			{Name: "code", DataType: schema.TypeString, Nullable: true},
			{Name: "translation", DataType: schema.TypeJSON, Nullable: true},
			{Name: "external_id", DataType: schema.TypeString, Nullable: true},
			{Name: "actions", DataType: schema.TypeJSON, Nullable: true},
		},
	},
	"groups": {
		Endpoint: "groups",
		Columns: []schema.Column{
			{Name: "group_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "name", DataType: schema.TypeString, Nullable: true},
			{Name: "description", DataType: schema.TypeString, Nullable: true},
			{Name: "language", DataType: schema.TypeString, Nullable: true},
			{Name: "total_members", DataType: schema.TypeInt64, Nullable: true},
			{Name: "id_branch", DataType: schema.TypeInt64, Nullable: true},
			{Name: "enrollment_rules", DataType: schema.TypeJSON, Nullable: true},
			{Name: "enrollment_rules_options", DataType: schema.TypeJSON, Nullable: true},
			{Name: "member_fields", DataType: schema.TypeJSON, Nullable: true},
			{Name: "is_default", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "creation_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "last_update", DataType: schema.TypeTimestampTZ, Nullable: true},
		},
	},
	"group_members": {
		Endpoint: "group_members",
		Columns: []schema.Column{
			{Name: "group_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "user_id", DataType: schema.TypeString, Nullable: true},
			{Name: "username", DataType: schema.TypeString, Nullable: true},
			{Name: "first_name", DataType: schema.TypeString, Nullable: true},
			{Name: "last_name", DataType: schema.TypeString, Nullable: true},
			{Name: "email", DataType: schema.TypeString, Nullable: true},
			{Name: "level", DataType: schema.TypeString, Nullable: true},
			{Name: "enrollment_date", DataType: schema.TypeTimestampTZ, Nullable: true},
		},
	},
	"course_fields": {
		Endpoint: "course_fields",
		Columns: []schema.Column{
			{Name: "field_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "type_field", DataType: schema.TypeString, Nullable: true},
			{Name: "name_field", DataType: schema.TypeString, Nullable: true},
			{Name: "is_mandatory", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "show_on_course_details", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "show_on_course_filter", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "options", DataType: schema.TypeJSON, Nullable: true},
			{Name: "sequence", DataType: schema.TypeInt64, Nullable: true},
		},
	},
	"learning_objects": {
		Endpoint: "learning_objects",
		Columns: []schema.Column{
			{Name: "course_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "id_org", DataType: schema.TypeInt64, Nullable: true},
			{Name: "object_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "lo_code", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_name", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_type", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_visibility", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_link", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_thumbnail", DataType: schema.TypeString, Nullable: true},
			{Name: "mobile_compatibility", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_external_source_url", DataType: schema.TypeString, Nullable: true},
			{Name: "created_by", DataType: schema.TypeString, Nullable: true},
			{Name: "creation_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "duration", DataType: schema.TypeInt64, Nullable: true},
		},
	},
	"learning_plans": {
		Endpoint: "learning_plans",
		Columns: []schema.Column{
			{Name: "learning_plan_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "uuid", DataType: schema.TypeString, Nullable: true},
			{Name: "code", DataType: schema.TypeString, Nullable: true},
			{Name: "title", DataType: schema.TypeString, Nullable: true},
			{Name: "thumbnail_url", DataType: schema.TypeString, Nullable: true},
			{Name: "price", DataType: schema.TypeString, Nullable: true},
			{Name: "credits", DataType: schema.TypeInt64, Nullable: true},
			{Name: "is_published", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "is_publishable", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "assigned_courses_count", DataType: schema.TypeInt64, Nullable: true},
			{Name: "assigned_enrollments_count", DataType: schema.TypeInt64, Nullable: true},
			{Name: "assigned_catalogs_count", DataType: schema.TypeInt64, Nullable: true},
			{Name: "assigned_channels_count", DataType: schema.TypeInt64, Nullable: true},
			{Name: "created_on", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "created_by", DataType: schema.TypeJSON, Nullable: true},
			{Name: "updated_on", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "updated_by", DataType: schema.TypeJSON, Nullable: true},
		},
	},
	"learning_plan_enrollments": {
		Endpoint: "learning_plan_enrollments",
		Columns: []schema.Column{
			{Name: "id_path", DataType: schema.TypeInt64, Nullable: true},
			{Name: "id_user", DataType: schema.TypeString, Nullable: true},
			{Name: "enrollment_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "completion_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "enrollment_status", DataType: schema.TypeString, Nullable: true},
			{Name: "score_given", DataType: schema.TypeFloat64, Nullable: true},
			{Name: "total_credits", DataType: schema.TypeInt64, Nullable: true},
			{Name: "total_time", DataType: schema.TypeInt64, Nullable: true},
			{Name: "completed_courses", DataType: schema.TypeInt64, Nullable: true},
			{Name: "total_courses", DataType: schema.TypeInt64, Nullable: true},
		},
	},
	"learning_plan_course_enrollments": {
		Endpoint: "learning_plan_course_enrollments",
		Columns: []schema.Column{
			{Name: "learning_plan_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "course_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "user_id", DataType: schema.TypeString, Nullable: true},
			{Name: "enrollment_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "completion_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "status", DataType: schema.TypeString, Nullable: true},
			{Name: "score", DataType: schema.TypeFloat64, Nullable: true},
			{Name: "credits", DataType: schema.TypeInt64, Nullable: true},
			{Name: "total_time", DataType: schema.TypeInt64, Nullable: true},
		},
	},
	"course_enrollments": {
		Endpoint: "course_enrollments",
		Columns: []schema.Column{
			{Name: "course_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "user_id", DataType: schema.TypeString, Nullable: true},
			{Name: "enrollment_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "completion_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "status", DataType: schema.TypeString, Nullable: true},
			{Name: "level", DataType: schema.TypeString, Nullable: true},
			{Name: "score_given", DataType: schema.TypeFloat64, Nullable: true},
			{Name: "score_total", DataType: schema.TypeFloat64, Nullable: true},
			{Name: "credits", DataType: schema.TypeInt64, Nullable: true},
			{Name: "total_time", DataType: schema.TypeInt64, Nullable: true},
			{Name: "expire_date", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "certificate_id", DataType: schema.TypeString, Nullable: true},
		},
	},
	"sessions": {
		Endpoint: "sessions",
		Columns: []schema.Column{
			{Name: "course_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "session_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "name", DataType: schema.TypeString, Nullable: true},
			{Name: "code", DataType: schema.TypeString, Nullable: true},
			{Name: "date_start", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "date_end", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "instructor", DataType: schema.TypeString, Nullable: true},
			{Name: "location", DataType: schema.TypeString, Nullable: true},
			{Name: "classroom", DataType: schema.TypeString, Nullable: true},
			{Name: "max_participants", DataType: schema.TypeInt64, Nullable: true},
			{Name: "enrolled_users", DataType: schema.TypeInt64, Nullable: true},
			{Name: "waiting_users", DataType: schema.TypeInt64, Nullable: true},
			{Name: "session_type", DataType: schema.TypeString, Nullable: true},
			{Name: "timezone", DataType: schema.TypeString, Nullable: true},
			{Name: "attendance_type", DataType: schema.TypeString, Nullable: true},
		},
	},
	"categories": {
		Endpoint: "categories",
		Columns: []schema.Column{
			{Name: "id_cat", DataType: schema.TypeInt64, Nullable: true},
			{Name: "code", DataType: schema.TypeString, Nullable: true},
			{Name: "description", DataType: schema.TypeString, Nullable: true},
			{Name: "id_parent", DataType: schema.TypeInt64, Nullable: true},
			{Name: "lft", DataType: schema.TypeInt64, Nullable: true},
			{Name: "rgt", DataType: schema.TypeInt64, Nullable: true},
			{Name: "is_active", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "translations", DataType: schema.TypeJSON, Nullable: true},
		},
	},
	"certifications": {
		Endpoint: "certifications",
		Columns: []schema.Column{
			{Name: "id_cert", DataType: schema.TypeInt64, Nullable: true},
			{Name: "code", DataType: schema.TypeString, Nullable: true},
			{Name: "title", DataType: schema.TypeString, Nullable: true},
			{Name: "description", DataType: schema.TypeString, Nullable: true},
			{Name: "type", DataType: schema.TypeString, Nullable: true},
			{Name: "validity_type", DataType: schema.TypeString, Nullable: true},
			{Name: "validity_days", DataType: schema.TypeInt64, Nullable: true},
			{Name: "renewal_available", DataType: schema.TypeBoolean, Nullable: true},
			{Name: "renewal_days_before", DataType: schema.TypeInt64, Nullable: true},
			{Name: "meta_language", DataType: schema.TypeString, Nullable: true},
			{Name: "meta_language_label", DataType: schema.TypeString, Nullable: true},
			{Name: "created_on", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "updated_on", DataType: schema.TypeTimestampTZ, Nullable: true},
		},
	},
	"external_training": {
		Endpoint: "external_training",
		Columns: []schema.Column{
			{Name: "external_training_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "user_id", DataType: schema.TypeString, Nullable: true},
			{Name: "title", DataType: schema.TypeString, Nullable: true},
			{Name: "description", DataType: schema.TypeString, Nullable: true},
			{Name: "training_type", DataType: schema.TypeString, Nullable: true},
			{Name: "provider", DataType: schema.TypeString, Nullable: true},
			{Name: "date_from", DataType: schema.TypeDate, Nullable: true},
			{Name: "date_to", DataType: schema.TypeDate, Nullable: true},
			{Name: "credits", DataType: schema.TypeInt64, Nullable: true},
			{Name: "score", DataType: schema.TypeFloat64, Nullable: true},
			{Name: "status", DataType: schema.TypeString, Nullable: true},
			{Name: "certificate_file", DataType: schema.TypeString, Nullable: true},
			{Name: "created_on", DataType: schema.TypeTimestampTZ, Nullable: true},
			{Name: "updated_on", DataType: schema.TypeTimestampTZ, Nullable: true},
		},
	},
	"polls": {
		Endpoint: "polls",
		Columns: []schema.Column{
			{Name: "poll_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "course_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "poll_title", DataType: schema.TypeString, Nullable: true},
			{Name: "object_type", DataType: schema.TypeString, Nullable: true},
			{Name: "lo_type", DataType: schema.TypeString, Nullable: true},
		},
	},
	"survey_answers": {
		Endpoint: "survey_answers",
		Columns: []schema.Column{
			{Name: "course_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "poll_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "poll_title", DataType: schema.TypeString, Nullable: true},
			{Name: "question_id", DataType: schema.TypeInt64, Nullable: true},
			{Name: "question_type", DataType: schema.TypeString, Nullable: true},
			{Name: "question_title", DataType: schema.TypeString, Nullable: true},
			{Name: "answer", DataType: schema.TypeString, Nullable: true},
			{Name: "date", DataType: schema.TypeTimestampTZ, Nullable: true},
		},
	},
}
