// Command genregistry scans pkg/source and pkg/destination directories
// and generates an imports file that triggers self-registration via init() functions.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	modulePrefix = "github.com/bruin-data/ingestr"
	outputFile   = "internal/registry/imports/imports.gen.go"
)

var skipDirs = map[string]bool{
	"adbc": true,
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	sources, err := findPackages("pkg/source")
	if err != nil {
		return fmt.Errorf("scanning sources: %w", err)
	}

	destinations, err := findPackages("pkg/destination")
	if err != nil {
		return fmt.Errorf("scanning destinations: %w", err)
	}

	content := generateFile(sources, destinations)

	if err := os.MkdirAll(filepath.Dir(outputFile), 0o755); err != nil {
		return fmt.Errorf("creating output directory: %w", err)
	}

	if err := os.WriteFile(outputFile, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing output file: %w", err)
	}

	fmt.Printf("Generated %s with %d sources and %d destinations\n",
		outputFile, len(sources), len(destinations))
	return nil
}

func findPackages(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var packages []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		name := entry.Name()
		if skipDirs[name] {
			continue
		}
		pkgPath := filepath.Join(dir, name)
		if hasGoFiles(pkgPath) && hasRegisterFile(pkgPath) {
			packages = append(packages, filepath.ToSlash(pkgPath))
		}
	}

	sort.Strings(packages)
	return packages, nil
}

func hasGoFiles(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, entry := range entries {
		if strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
			return true
		}
	}
	return false
}

func hasRegisterFile(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, "register.go"))
	return err == nil
}

func generateFile(sources, destinations []string) string {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/genregistry. DO NOT EDIT.\n\n")
	b.WriteString("package imports\n\n")
	b.WriteString("import (\n")

	// Write destinations first, then sources (formatter requires this order)
	for _, pkg := range destinations {
		fmt.Fprintf(&b, "\t_ \"%s/%s\"\n", modulePrefix, pkg)
	}
	for _, pkg := range sources {
		fmt.Fprintf(&b, "\t_ \"%s/%s\"\n", modulePrefix, pkg)
	}

	b.WriteString(")\n")

	return b.String()
}
