#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_file="$repo_root/THIRD_PARTY_LICENSES.txt"
check_only=0

if [[ "${1:-}" == "--check" ]]; then
	check_only=1
	shift
fi

if [[ $# -gt 0 ]]; then
	output_file="$1"
fi

go_licenses_module="${GO_LICENSES_MODULE:-github.com/google/go-licenses@v1.6.0}"
disallowed_license_types="${LICENSE_DISALLOWED_TYPES:-forbidden,restricted,unknown}"
packages="${LICENSE_PACKAGES:-./...}"
module_path="$(cd "$repo_root" && go list -m)"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

go_licenses_log="$tmpdir/go-licenses.log"
go_licenses_out="$tmpdir/go-licenses.out"

run_go_licenses() {
	: >"$go_licenses_log"
	: >"$go_licenses_out"

	if ! (cd "$repo_root" && go run "$go_licenses_module" "$@" >"$go_licenses_out" 2>"$go_licenses_log"); then
		if [[ -s "$go_licenses_out" ]]; then
			cat "$go_licenses_out" >&2
		fi
		if [[ -s "$go_licenses_log" ]]; then
			cat "$go_licenses_log" >&2
		fi
		return 1
	fi
}

sha256_file() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | awk '{print $1}'
	else
		shasum -a 256 "$1" | awk '{print $1}'
	fi
}

copy_notice_file() {
	local rel="$1"
	local abs="$2"
	local out="$3"

	{
		printf '\n'
		printf '===============================================================================\n'
		printf '%s\n' "$rel"
		printf '===============================================================================\n\n'
		cat "$abs"
		printf '\n'
	} >>"$out"
}

append_manual_module_license() {
	local module="$1"
	local expected_version="$2"
	local license_file="$3"
	local license_name="$4"
	local expected_sha256="$5"
	local out="$6"

	local module_info version dir selected_sha256

	if ! module_info="$(cd "$repo_root" && go list -m -f '{{.Version}}	{{.Dir}}' "$module" 2>/dev/null)"; then
		return 0
	fi

	version="${module_info%%	*}"
	dir="${module_info#*	}"

	if [[ "$version" != "$expected_version" ]]; then
		cat >&2 <<EOF
Manual license audit for $module is pinned to $expected_version, but go.mod selects $version.
Review $module's license, then update hack/update-third-party-licenses.sh and regenerate THIRD_PARTY_LICENSES.txt.
EOF
		return 1
	fi

	if [[ ! -f "$dir/$license_file" ]]; then
		cat >&2 <<EOF
Manual license audit for $module expected $license_file, but it was not found in $dir.
Review $module's license, then update hack/update-third-party-licenses.sh and regenerate THIRD_PARTY_LICENSES.txt.
EOF
		return 1
	fi

	selected_sha256="$(sha256_file "$dir/$license_file")"
	if [[ "$selected_sha256" != "$expected_sha256" ]]; then
		cat >&2 <<EOF
Manual license audit for $module expected SHA-256 $expected_sha256, but found $selected_sha256.
Review $module's license, then update hack/update-third-party-licenses.sh and regenerate THIRD_PARTY_LICENSES.txt.
EOF
		return 1
	fi

	{
		printf '\n'
		printf '===============================================================================\n'
		printf '%s/%s (%s, manually audited)\n' "$module" "$license_file" "$license_name"
		printf '===============================================================================\n\n'
		cat "$dir/$license_file"
		printf '\n'
	} >>"$out"
}

save_dir="$tmpdir/go-licenses"
generated_file="$tmpdir/THIRD_PARTY_LICENSES.txt"

ignore_flags=(
	--ignore "$module_path"
	# go-licenses v1.6.0 cannot classify these current license files. Keep them
	# pinned below so version or license text changes force a manual review.
	--ignore "github.com/segmentio/asm"
	--ignore "modernc.org/mathutil"
)

run_go_licenses check "$packages" \
	--include_tests \
	"${ignore_flags[@]}" \
	--disallowed_types="$disallowed_license_types"

run_go_licenses save "$packages" \
	--include_tests \
	"${ignore_flags[@]}" \
	--save_path "$save_dir"

{
	printf 'Third-Party Licenses\n'
	printf '\n'
	printf 'This file contains third-party Go dependency license notices for ingestr.\n'
	printf 'It is generated by hack/update-third-party-licenses.sh; do not edit it manually.\n'
	printf '\n'
	printf 'Generator: %s\n' "$go_licenses_module"
	printf 'Packages: %s\n' "$packages"
	printf 'Disallowed license types: %s\n' "$disallowed_license_types"
	printf '\n'
} >"$generated_file"

while IFS= read -r file; do
	rel="${file#"$save_dir"/}"
	copy_notice_file "$rel" "$file" "$generated_file"
done < <(
	find "$save_dir" -type f \
		\( \
			-iname 'LICENSE*' -o \
			-iname 'LICENCE*' -o \
			-iname 'COPYING*' -o \
			-iname 'NOTICE*' -o \
			-iname 'AUTHORS' -o \
			-iname 'PATENTS' \
		\) \
		| LC_ALL=C sort
)

while IFS= read -r dir; do
	if ! find "$dir" -maxdepth 1 -type f \
		\( \
			-iname 'LICENSE*' -o \
			-iname 'LICENCE*' -o \
			-iname 'COPYING*' -o \
			-iname 'NOTICE*' \
		\) | grep -q .; then
		while IFS= read -r readme; do
			rel="${readme#"$save_dir"/}"
			copy_notice_file "$rel" "$readme" "$generated_file"
		done < <(find "$dir" -maxdepth 1 -type f -iname 'README*' | LC_ALL=C sort)
	fi
done < <(find "$save_dir" -type d | LC_ALL=C sort)

append_manual_module_license \
	"github.com/segmentio/asm" \
	"v1.2.1" \
	"LICENSE" \
	"MIT No Attribution" \
	"cca993712df289a5958bdef69031a5dac0f951ac15afeb313f9eeea55ed59443" \
	"$generated_file"

append_manual_module_license \
	"modernc.org/mathutil" \
	"v1.7.1" \
	"LICENSE" \
	"BSD-3-Clause" \
	"bfa9bf72a72ca009fd62a8f84fca3dca67e51d93af96352723646599898b6cf5" \
	"$generated_file"

if [[ "$check_only" -eq 1 ]]; then
	if ! cmp -s "$generated_file" "$output_file"; then
		cat >&2 <<EOF
$output_file is stale.
Run 'make licenses' and commit the updated THIRD_PARTY_LICENSES.txt.
EOF
		diff -u "$output_file" "$generated_file" >&2 || true
		exit 1
	fi
else
	cp "$generated_file" "$output_file"
fi
