#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_file="$repo_root/THIRD_PARTY_LICENSES.txt"
check_only=0
policy_only=0

while [[ $# -gt 0 ]]; do
	case "$1" in
		--check)
			check_only=1
			shift
			;;
		--policy-only)
			policy_only=1
			shift
			;;
		*)
			output_file="$1"
			shift
			;;
	esac
done

if [[ "$check_only" -eq 1 && "$policy_only" -eq 1 ]]; then
	echo "--check and --policy-only cannot be used together" >&2
	exit 1
fi

go_licenses_module="${GO_LICENSES_MODULE:-github.com/google/go-licenses@v1.6.0}"
disallowed_license_types="${LICENSE_DISALLOWED_TYPES:-forbidden,restricted,unknown}"
packages="${LICENSE_PACKAGES:-./...}"
license_targets="${LICENSE_TARGETS:-linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64}"
include_tests="${LICENSE_INCLUDE_TESTS:-true}"
license_lock_file="${LICENSE_LOCK_FILE:-$repo_root/licenses.lock.yml}"
module_path="$(cd "$repo_root" && go list -m)"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

go_licenses_bin="$tmpdir/bin/go-licenses$(go env GOEXE)"
active_goroot="$(go env GOROOT)"

(cd "$repo_root" && GOBIN="$tmpdir/bin" go install "$go_licenses_module")

copy_notice_file() {
	local rel="$1"
	local abs="$2"
	local out="$3"

	{
		printf '\n'
		printf '===============================================================================\n'
		printf '%s\n' "$rel"
		printf '===============================================================================\n\n'
		sed 's/[[:blank:]]*$//' "$abs"
		printf '\n'
	} >>"$out"
}

append_manual_module_licenses() {
	local out="$1"

	(cd "$repo_root" && go run ./cmd/licenseaudit --mode append-manual-notices --lock "$license_lock_file" --output "$out")
}

save_root="$tmpdir/go-licenses"
generated_file="$tmpdir/THIRD_PARTY_LICENSES.txt"

ignore_flags=(
	--ignore "$module_path"
)

while IFS= read -r module; do
	if [[ -n "$module" ]]; then
		ignore_flags+=(--ignore "$module")
	fi
done < <((cd "$repo_root" && go run ./cmd/licenseaudit --mode ignored-modules --lock "$license_lock_file"))

license_test_flags=()
case "$include_tests" in
	1 | true | TRUE | yes | YES)
		license_test_flags=(--include_tests)
		;;
	0 | false | FALSE | no | NO | "")
		;;
	*)
		echo "LICENSE_INCLUDE_TESTS must be true or false, got: $include_tests" >&2
		exit 1
		;;
esac

run_target() {
	local target="$1"
	local goos="${target%/*}"
	local goarch="${target#*/}"
	local label="$goos-$goarch"
	local target_save_dir="$save_root/$label"
	local target_out="$tmpdir/$label.out"
	local target_log="$tmpdir/$label.log"
	local target_failure="$tmpdir/$label.failed"

	if ! (cd "$repo_root" && GOOS="$goos" GOARCH="$goarch" GOROOT="$active_goroot" "$go_licenses_bin" check "$packages" \
		"${license_test_flags[@]}" \
		"${ignore_flags[@]}" \
		--disallowed_types="$disallowed_license_types" \
		>"$target_out" 2>"$target_log"); then
		{
			printf 'go-licenses check failed for %s\n' "$target"
			cat "$target_out"
			cat "$target_log"
		} >"$target_failure"
		return 1
	fi

	if [[ "$policy_only" -eq 1 ]]; then
		return 0
	fi

	if ! (cd "$repo_root" && GOOS="$goos" GOARCH="$goarch" GOROOT="$active_goroot" "$go_licenses_bin" save "$packages" \
		"${license_test_flags[@]}" \
		"${ignore_flags[@]}" \
		--save_path "$target_save_dir" \
		>"$target_out" 2>"$target_log"); then
		{
			printf 'go-licenses save failed for %s\n' "$target"
			cat "$target_out"
			cat "$target_log"
		} >"$target_failure"
		return 1
	fi
}

pids=()
for target in $license_targets; do
	run_target "$target" &
	pids+=("$!")
done

failed=0
for pid in "${pids[@]}"; do
	if ! wait "$pid"; then
		failed=1
	fi
done

if [[ "$failed" -ne 0 ]]; then
	while IFS= read -r failure; do
		cat "$failure" >&2
	done < <(find "$tmpdir" -maxdepth 1 -type f -name '*.failed' | LC_ALL=C sort)
	exit 1
fi

if [[ "$policy_only" -eq 1 ]]; then
	manual_license_file="$tmpdir/manual-licenses.txt"
	: >"$manual_license_file"
	append_manual_module_licenses "$manual_license_file"
	exit 0
fi

{
	printf 'Third-Party Licenses\n'
	printf '\n'
	printf 'This file contains third-party Go dependency license notices for ingestr.\n'
	printf 'It is generated by hack/update-third-party-licenses.sh; do not edit it manually.\n'
	printf '\n'
	printf 'Generator: %s\n' "$go_licenses_module"
	printf 'Packages: %s\n' "$packages"
	printf 'License targets: %s\n' "$license_targets"
	printf 'Disallowed license types: %s\n' "$disallowed_license_types"
	printf '\n'
} >"$generated_file"

notice_entries="$tmpdir/notice-entries.tsv"
: >"$notice_entries"

while IFS= read -r target_dir; do
	while IFS= read -r file; do
		rel="${file#"$target_dir"/}"
		printf '%s\t%s\n' "$rel" "$file" >>"$notice_entries"
	done < <(
		find "$target_dir" -type f \
			\( \
				-iname 'LICENSE*' -o \
				-iname 'LICENCE*' -o \
				-iname 'COPYING*' -o \
				-iname 'NOTICE*' -o \
				-iname 'AUTHORS' -o \
				-iname 'PATENTS' \
			\) \
			| LC_ALL=C sort
	)

	while IFS= read -r dir; do
		if ! find "$dir" -maxdepth 1 -type f \
			\( \
				-iname 'LICENSE*' -o \
				-iname 'LICENCE*' -o \
				-iname 'COPYING*' -o \
				-iname 'NOTICE*' \
			\) | grep -q .; then
			while IFS= read -r readme; do
				rel="${readme#"$target_dir"/}"
				printf '%s\t%s\n' "$rel" "$readme" >>"$notice_entries"
			done < <(find "$dir" -maxdepth 1 -type f -iname 'README*' | LC_ALL=C sort)
		fi
	done < <(find "$target_dir" -type d | LC_ALL=C sort)
done < <(find "$save_root" -mindepth 1 -maxdepth 1 -type d | LC_ALL=C sort)

LC_ALL=C sort "$notice_entries" | awk -F '\t' '!seen[$1]++' | while IFS=$'\t' read -r rel file; do
	# go-licenses can emit both the historical GitHub casing and the canonical
	# module casing for go-mssqldb on some hosts. Keep one copy.
	if [[ "$rel" == github.com/Microsoft/go-mssqldb/* ]]; then
		continue
	fi

	copy_notice_file "$rel" "$file" "$generated_file"
done

append_manual_module_licenses "$generated_file"

if [[ "$check_only" -eq 1 ]]; then
	if ! cmp -s "$generated_file" "$output_file"; then
		cat >&2 <<EOF
$output_file is stale.
Run 'make licenses' and commit the updated THIRD_PARTY_LICENSES.txt.
EOF
		diff -u "$output_file" "$generated_file" >&2 || true
		exit 1
	fi
else
	cp "$generated_file" "$output_file"
fi
