[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.clickhouse]
dataset_table_separator = "___"
table_engine_type = "merge_tree"
dataset_sentinel_table_name = "dlt_sentinel_table"
[destination.clickhouse.credentials]
database = "default"
password = "password" # please set me up!
username = "default"
host = "host" # please set me up!
port = 9440
http_port = 8443
