[sources.chess]
secret_str = "secret_str" # please set me up!

[sources.chess.secret_dict] # please set me up!
key = "value"

[destination.athena]
query_result_bucket = "s3://querybucket535"
athena_work_group = "my_group"

[destination.athena.credentials]
aws_access_key_id = ""
aws_secret_access_key = ""
region_name = "eu-central-1"

[destination.filesystem]
bucket_url = "s3://destbuct535"

[destination.filesystem.credentials]
aws_access_key_id = "AKIARCCG3YOWXSA5NJ55"
aws_secret_access_key = "u"
