package pipedrive_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/bruin-data/ingestr/internal/testutil"
	"github.com/bruin-data/ingestr/pkg/schema"
)

func TestPipedrivePipeline(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	apiToken := os.Getenv("PIPEDRIVE_API_TOKEN")
	if apiToken == "" {
		t.Skip("Set PIPEDRIVE_API_TOKEN to run Pipedrive integration tests")
	}

	ctx := context.Background()
	sourceURI := fmt.Sprintf("pipedrive://?api_token=%s", apiToken)

	tmpDir := t.TempDir()
	dbPath := filepath.Join(tmpDir, fmt.Sprintf("pipedrive_%d.duckdb", time.Now().UnixNano()))
	destURI := fmt.Sprintf("duckdb:///%s", dbPath)

	expectations := []testutil.TableExpectation{
		{
			SourceTable:      "activities",
			DestTable:        "main.pipedrive_activities",
			KeyColumn:        "id",
			ExpectedRowCount: 2,
			ExpectedSchema: []schema.Column{
				{Name: "active_flag", DataType: schema.TypeBoolean},
				{Name: "add_time", DataType: schema.TypeTimestampTZ},
				{Name: "assigned_to_user_id", DataType: schema.TypeInt64},
				{Name: "busy_flag", DataType: schema.TypeBoolean},
				{Name: "company_id", DataType: schema.TypeInt64},
				{Name: "created_by_user_id", DataType: schema.TypeInt64},
				{Name: "deal_dropbox_bcc", DataType: schema.TypeString},
				{Name: "deal_id", DataType: schema.TypeInt64},
				{Name: "deal_title", DataType: schema.TypeString},
				{Name: "done", DataType: schema.TypeBoolean},
				{Name: "due_date", DataType: schema.TypeDate},
				{Name: "due_time", DataType: schema.TypeString},
				{Name: "duration", DataType: schema.TypeString},
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "marked_as_done_time", DataType: schema.TypeString},
				{Name: "org_id", DataType: schema.TypeInt64},
				{Name: "org_name", DataType: schema.TypeString},
				{Name: "owner_name", DataType: schema.TypeString},
				{Name: "person_dropbox_bcc", DataType: schema.TypeString},
				{Name: "person_id", DataType: schema.TypeInt64},
				{Name: "person_name", DataType: schema.TypeString},
				{Name: "private", DataType: schema.TypeBoolean},
				{Name: "subject", DataType: schema.TypeString},
				{Name: "type", DataType: schema.TypeString},
				{Name: "type_name", DataType: schema.TypeString},
				{Name: "update_time", DataType: schema.TypeTimestampTZ},
				{Name: "user_id", DataType: schema.TypeInt64},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "1",
					Fields: map[string]any{
						"subject":     "Test Activity Call",
						"type":        "call",
						"type_name":   "Call",
						"done":        false,
						"due_time":    "10:00",
						"deal_id":     int64(1),
						"deal_title":  "Test Deal",
						"org_id":      int64(1),
						"org_name":    "Test Organization Inc",
						"person_id":   int64(1),
						"person_name": "John Test",
						"owner_name":  "Vendor Accounts",
						"busy_flag":   true,
						"private":     false,
						"user_id":     int64(25391939),
					},
				},
			},
		},
		{
			SourceTable:      "deals",
			DestTable:        "main.pipedrive_deals",
			KeyColumn:        "id",
			ExpectedRowCount: 2,
			ExpectedSchema: []schema.Column{
				{Name: "active", DataType: schema.TypeBoolean},
				{Name: "activities_count", DataType: schema.TypeInt64},
				{Name: "add_time", DataType: schema.TypeTimestampTZ},
				{Name: "cc_email", DataType: schema.TypeString},
				{Name: "creator_user_id", DataType: schema.TypeInt64},
				{Name: "currency", DataType: schema.TypeString},
				{Name: "deleted", DataType: schema.TypeBoolean},
				{Name: "done_activities_count", DataType: schema.TypeInt64},
				{Name: "email_messages_count", DataType: schema.TypeInt64},
				{Name: "files_count", DataType: schema.TypeInt64},
				{Name: "followers_count", DataType: schema.TypeInt64},
				{Name: "formatted_value", DataType: schema.TypeString},
				{Name: "formatted_weighted_value", DataType: schema.TypeString},
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "is_archived", DataType: schema.TypeBoolean},
				{Name: "next_activity_date", DataType: schema.TypeDate},
				{Name: "next_activity_id", DataType: schema.TypeInt64},
				{Name: "next_activity_subject", DataType: schema.TypeString},
				{Name: "next_activity_time", DataType: schema.TypeString},
				{Name: "next_activity_type", DataType: schema.TypeString},
				{Name: "notes_count", DataType: schema.TypeInt64},
				{Name: "org_hidden", DataType: schema.TypeBoolean},
				{Name: "org_id", DataType: schema.TypeInt64},
				{Name: "org_name", DataType: schema.TypeString},
				{Name: "origin", DataType: schema.TypeString},
				{Name: "owner_name", DataType: schema.TypeString},
				{Name: "participants_count", DataType: schema.TypeInt64},
				{Name: "person_hidden", DataType: schema.TypeBoolean},
				{Name: "person_id", DataType: schema.TypeInt64},
				{Name: "person_name", DataType: schema.TypeString},
				{Name: "pipeline_id", DataType: schema.TypeInt64},
				{Name: "products_count", DataType: schema.TypeInt64},
				{Name: "stage_id", DataType: schema.TypeInt64},
				{Name: "stage_order_nr", DataType: schema.TypeInt64},
				{Name: "status", DataType: schema.TypeString},
				{Name: "title", DataType: schema.TypeString},
				{Name: "undone_activities_count", DataType: schema.TypeInt64},
				{Name: "update_time", DataType: schema.TypeTimestampTZ},
				{Name: "user_id", DataType: schema.TypeInt64},
				{Name: "value", DataType: schema.TypeInt64},
				{Name: "visible_to", DataType: schema.TypeString},
				{Name: "weighted_value", DataType: schema.TypeInt64},
				{Name: "weighted_value_currency", DataType: schema.TypeString},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "1",
					Fields: map[string]any{
						"title":                    "Test Deal",
						"status":                   "open",
						"currency":                 "USD",
						"value":                    int64(5000),
						"org_id":                   int64(1),
						"org_name":                 "Test Organization Inc",
						"person_id":                int64(1),
						"person_name":              "John Test",
						"owner_name":               "Vendor Accounts",
						"user_id":                  int64(25391939),
						"creator_user_id":          int64(25391939),
						"pipeline_id":              int64(2),
						"stage_id":                 int64(6),
						"stage_order_nr":           int64(1),
						"active":                   true,
						"deleted":                  false,
						"is_archived":              false,
						"origin":                   "API",
						"visible_to":               "3",
						"formatted_value":          "$5.000",
						"weighted_value":           int64(5000),
						"weighted_value_currency":  "USD",
						"formatted_weighted_value": "$5.000",
						"activities_count":         int64(1),
						"undone_activities_count":  int64(1),
						"done_activities_count":    int64(0),
						"followers_count":          int64(1),
						"participants_count":       int64(1),
					},
				},
			},
		},
		{
			SourceTable:      "persons",
			DestTable:        "main.pipedrive_persons",
			KeyColumn:        "id",
			ExpectedRowCount: 2,
			ExpectedSchema: []schema.Column{
				{Name: "active_flag", DataType: schema.TypeBoolean},
				{Name: "activities_count", DataType: schema.TypeInt64},
				{Name: "add_time", DataType: schema.TypeTimestampTZ},
				{Name: "cc_email", DataType: schema.TypeString},
				{Name: "closed_deals_count", DataType: schema.TypeInt64},
				{Name: "company_id", DataType: schema.TypeInt64},
				{Name: "done_activities_count", DataType: schema.TypeInt64},
				{Name: "email_messages_count", DataType: schema.TypeInt64},
				{Name: "files_count", DataType: schema.TypeInt64},
				{Name: "first_char", DataType: schema.TypeString},
				{Name: "first_name", DataType: schema.TypeString},
				{Name: "followers_count", DataType: schema.TypeInt64},
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "last_name", DataType: schema.TypeString},
				{Name: "lost_deals_count", DataType: schema.TypeInt64},
				{Name: "name", DataType: schema.TypeString},
				{Name: "next_activity_date", DataType: schema.TypeDate},
				{Name: "next_activity_id", DataType: schema.TypeInt64},
				{Name: "next_activity_time", DataType: schema.TypeString},
				{Name: "notes_count", DataType: schema.TypeInt64},
				{Name: "open_deals_count", DataType: schema.TypeInt64},
				{Name: "org_id", DataType: schema.TypeInt64},
				{Name: "org_name", DataType: schema.TypeString},
				{Name: "owner_id", DataType: schema.TypeInt64},
				{Name: "owner_name", DataType: schema.TypeString},
				{Name: "participant_closed_deals_count", DataType: schema.TypeInt64},
				{Name: "participant_open_deals_count", DataType: schema.TypeInt64},
				{Name: "related_closed_deals_count", DataType: schema.TypeInt64},
				{Name: "related_lost_deals_count", DataType: schema.TypeInt64},
				{Name: "related_open_deals_count", DataType: schema.TypeInt64},
				{Name: "related_won_deals_count", DataType: schema.TypeInt64},
				{Name: "undone_activities_count", DataType: schema.TypeInt64},
				{Name: "update_time", DataType: schema.TypeTimestampTZ},
				{Name: "visible_to", DataType: schema.TypeString},
				{Name: "won_deals_count", DataType: schema.TypeInt64},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "1",
					Fields: map[string]any{
						"name":               "John Test",
						"first_name":         "John",
						"last_name":          "Test",
						"first_char":         "j",
						"active_flag":        true,
						"visible_to":         "3",
						"org_id":             int64(1),
						"org_name":           "Test Organization Inc",
						"owner_id":           int64(25391939),
						"owner_name":         "Vendor Accounts",
						"open_deals_count":   int64(1),
						"closed_deals_count": int64(0),
						"lost_deals_count":   int64(0),
						"won_deals_count":    int64(0),
						"activities_count":   int64(1),
						"followers_count":    int64(1),
					},
				},
			},
		},
		{
			SourceTable:      "organizations",
			DestTable:        "main.pipedrive_organizations",
			KeyColumn:        "id",
			ExpectedRowCount: 2,
			ExpectedSchema: []schema.Column{
				{Name: "active_flag", DataType: schema.TypeBoolean},
				{Name: "activities_count", DataType: schema.TypeInt64},
				{Name: "add_time", DataType: schema.TypeTimestampTZ},
				{Name: "cc_email", DataType: schema.TypeString},
				{Name: "closed_deals_count", DataType: schema.TypeInt64},
				{Name: "company_id", DataType: schema.TypeInt64},
				{Name: "done_activities_count", DataType: schema.TypeInt64},
				{Name: "email_messages_count", DataType: schema.TypeInt64},
				{Name: "files_count", DataType: schema.TypeInt64},
				{Name: "first_char", DataType: schema.TypeString},
				{Name: "followers_count", DataType: schema.TypeInt64},
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "lost_deals_count", DataType: schema.TypeInt64},
				{Name: "name", DataType: schema.TypeString},
				{Name: "next_activity_date", DataType: schema.TypeDate},
				{Name: "next_activity_id", DataType: schema.TypeInt64},
				{Name: "next_activity_time", DataType: schema.TypeString},
				{Name: "notes_count", DataType: schema.TypeInt64},
				{Name: "open_deals_count", DataType: schema.TypeInt64},
				{Name: "owner_id", DataType: schema.TypeInt64},
				{Name: "owner_name", DataType: schema.TypeString},
				{Name: "people_count", DataType: schema.TypeInt64},
				{Name: "related_closed_deals_count", DataType: schema.TypeInt64},
				{Name: "related_lost_deals_count", DataType: schema.TypeInt64},
				{Name: "related_open_deals_count", DataType: schema.TypeInt64},
				{Name: "related_won_deals_count", DataType: schema.TypeInt64},
				{Name: "undone_activities_count", DataType: schema.TypeInt64},
				{Name: "update_time", DataType: schema.TypeTimestampTZ},
				{Name: "visible_to", DataType: schema.TypeString},
				{Name: "won_deals_count", DataType: schema.TypeInt64},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "1",
					Fields: map[string]any{
						"name":               "Test Organization Inc",
						"first_char":         "t",
						"active_flag":        true,
						"visible_to":         "3",
						"owner_id":           int64(25391939),
						"owner_name":         "Vendor Accounts",
						"people_count":       int64(1),
						"open_deals_count":   int64(1),
						"closed_deals_count": int64(0),
						"lost_deals_count":   int64(0),
						"won_deals_count":    int64(0),
						"activities_count":   int64(1),
						"followers_count":    int64(1),
					},
				},
			},
		},
		{
			SourceTable:      "products",
			DestTable:        "main.pipedrive_products",
			KeyColumn:        "id",
			ExpectedRowCount: 2,
			ExpectedSchema: []schema.Column{
				{Name: "active_flag", DataType: schema.TypeBoolean},
				{Name: "add_time", DataType: schema.TypeTimestampTZ},
				{Name: "billing_frequency", DataType: schema.TypeString},
				{Name: "code", DataType: schema.TypeString},
				{Name: "first_char", DataType: schema.TypeString},
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "name", DataType: schema.TypeString},
				{Name: "owner_id", DataType: schema.TypeInt64},
				{Name: "owner_name", DataType: schema.TypeString},
				{Name: "selectable", DataType: schema.TypeBoolean},
				{Name: "tax", DataType: schema.TypeInt64},
				{Name: "unit", DataType: schema.TypeString},
				{Name: "update_time", DataType: schema.TypeTimestampTZ},
				{Name: "visible_to", DataType: schema.TypeString},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "1",
					Fields: map[string]any{
						"name":              "Test Product",
						"code":              "TP001",
						"first_char":        "t",
						"active_flag":       true,
						"selectable":        true,
						"tax":               int64(0),
						"unit":              "piece",
						"billing_frequency": "one-time",
						"visible_to":        "3",
						"owner_id":          int64(25391939),
						"owner_name":        "Vendor Accounts",
					},
				},
			},
		},
		{
			SourceTable:      "users",
			DestTable:        "main.pipedrive_users",
			KeyColumn:        "id",
			ExpectedRowCount: 1,
			ExpectedSchema: []schema.Column{
				{Name: "active_flag", DataType: schema.TypeBoolean},
				{Name: "created", DataType: schema.TypeTimestampTZ},
				{Name: "default_currency", DataType: schema.TypeString},
				{Name: "email", DataType: schema.TypeString},
				{Name: "has_created_company", DataType: schema.TypeBoolean},
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "is_admin", DataType: schema.TypeInt64},
				{Name: "is_you", DataType: schema.TypeBoolean},
				{Name: "lang", DataType: schema.TypeInt64},
				{Name: "last_login", DataType: schema.TypeTimestampTZ},
				{Name: "locale", DataType: schema.TypeString},
				{Name: "modified", DataType: schema.TypeTimestampTZ},
				{Name: "name", DataType: schema.TypeString},
				{Name: "phone", DataType: schema.TypeString},
				{Name: "role_id", DataType: schema.TypeInt64},
				{Name: "signup_flow_variation", DataType: schema.TypeString},
				{Name: "timezone_name", DataType: schema.TypeString},
				{Name: "timezone_offset", DataType: schema.TypeString},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "25391939",
					Fields: map[string]any{
						"name":                "Vendor Accounts",
						"email":               "vendor_accounts@getbruin.com",
						"active_flag":         true,
						"is_admin":            int64(1),
						"is_you":              true,
						"has_created_company": false,
						"default_currency":    "TRY",
						"locale":              "tr_TR",
						"lang":                int64(1),
						"role_id":             int64(1),
						"timezone_name":       "Europe/Istanbul",
						"timezone_offset":     "+03:00",
						"phone":               "+905551234567",
					},
				},
			},
		},
	}

	for _, exp := range expectations {
		t.Run(exp.SourceTable, func(t *testing.T) {
			testutil.RunPipeline(t, ctx, sourceURI, destURI, exp)
			testutil.Check(t, destURI, exp)
		})
	}
}
