package shopify_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/bruin-data/ingestr/internal/testutil"
	"github.com/bruin-data/ingestr/pkg/schema"
)

func TestShopifyPipeline(t *testing.T) {
	if testing.Short() {
		t.Skip("Skipping integration test in short mode")
	}

	store := os.Getenv("SHOPIFY_STORE")
	apiKey := os.Getenv("SHOPIFY_API_KEY")
	clientID := os.Getenv("SHOPIFY_CLIENT_ID")
	clientSecret := os.Getenv("SHOPIFY_CLIENT_SECRET")

	if store == "" {
		t.Skip("Set SHOPIFY_STORE to run Shopify integration tests")
	}
	if apiKey == "" && (clientID == "" || clientSecret == "") {
		t.Skip("Set SHOPIFY_API_KEY or both SHOPIFY_CLIENT_ID and SHOPIFY_CLIENT_SECRET to run Shopify integration tests")
	}

	ctx := context.Background()
	var sourceURI string
	if apiKey != "" {
		sourceURI = fmt.Sprintf("shopify://%s?api_key=%s", store, apiKey)
	} else {
		sourceURI = fmt.Sprintf("shopify://%s?client_id=%s&client_secret=%s", store, clientID, clientSecret)
	}

	tmpDir := t.TempDir()
	dbPath := filepath.Join(tmpDir, fmt.Sprintf("shopify_%d.duckdb", time.Now().UnixNano()))
	destURI := fmt.Sprintf("duckdb:///%s", dbPath)

	expectations := []testutil.TableExpectation{
		{
			SourceTable: "products",
			DestTable:   "main.shopify_products",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "admin_graphql_api_id", DataType: schema.TypeString},
				{Name: "title", DataType: schema.TypeString},
				{Name: "handle", DataType: schema.TypeString},
				{Name: "body_html", DataType: schema.TypeString},
				{Name: "vendor", DataType: schema.TypeString},
				{Name: "product_type", DataType: schema.TypeString},
				{Name: "status", DataType: schema.TypeString},
				{Name: "tags", DataType: schema.TypeString},
				{Name: "template_suffix", DataType: schema.TypeString},
				{Name: "created_at", DataType: schema.TypeTimestampTZ},
				{Name: "updated_at", DataType: schema.TypeTimestampTZ},
				{Name: "published_at", DataType: schema.TypeTimestampTZ},
				{Name: "published_scope", DataType: schema.TypeString},
				{Name: "variants", DataType: schema.TypeJSON},
				{Name: "options", DataType: schema.TypeJSON},
				{Name: "images", DataType: schema.TypeJSON},
				{Name: "image", DataType: schema.TypeJSON},
			},
			ExpectedRowCount: 2,
			Rows: []testutil.ExpectedRow{
				{
					ID: "8671508725848",
					Fields: map[string]any{
						"admin_graphql_api_id": "gid://shopify/Product/8671508725848",
						"title":                "Gong Test Mug",
						"handle":               "gong-test-mug",
						"body_html":            "<p>A ceramic mug for testing purposes.</p>",
						"vendor":               "GongTest",
						"product_type":         "Accessories",
						"status":               "active",
						"tags":                 "ceramic, mug, test",
						"template_suffix":      nil,
						"created_at":           time.Date(2026, 2, 16, 5, 16, 53, 0, time.UTC),
						"published_at":         time.Date(2026, 2, 16, 5, 16, 53, 0, time.UTC),
						"published_scope":      "global",
					},
				},
				{
					ID: "8671510233176",
					Fields: map[string]any{
						"admin_graphql_api_id": "gid://shopify/Product/8671510233176",
						"title":                "Gong Test T-Shirt",
						"handle":               "gong-test-t-shirt",
						"body_html":            "<p>A comfortable cotton t-shirt for testing.</p>",
						"vendor":               "GongTest",
						"product_type":         "Clothing",
						"status":               "active",
						"tags":                 "clothing, cotton, test",
						"template_suffix":      nil,
						"created_at":           time.Date(2026, 2, 16, 5, 17, 59, 0, time.UTC),
						"published_at":         time.Date(2026, 2, 16, 5, 17, 59, 0, time.UTC),
						"published_scope":      "global",
					},
				},
			},
		},
		{
			SourceTable: "customers",
			DestTable:   "main.shopify_customers",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "admin_graphql_api_id", DataType: schema.TypeString},
				{Name: "email", DataType: schema.TypeString},
				{Name: "first_name", DataType: schema.TypeString},
				{Name: "last_name", DataType: schema.TypeString},
				{Name: "phone", DataType: schema.TypeString},
				{Name: "created_at", DataType: schema.TypeTimestampTZ},
				{Name: "updated_at", DataType: schema.TypeTimestampTZ},
				{Name: "state", DataType: schema.TypeString},
				{Name: "note", DataType: schema.TypeString},
				{Name: "tags", DataType: schema.TypeString},
				{Name: "tax_exempt", DataType: schema.TypeBoolean},
				{Name: "tax_exemptions", DataType: schema.TypeJSON},
				{Name: "verified_email", DataType: schema.TypeBoolean},
				{Name: "multipass_identifier", DataType: schema.TypeString},
				{Name: "accepts_marketing", DataType: schema.TypeBoolean},
				{Name: "accepts_marketing_updated_at", DataType: schema.TypeTimestampTZ},
				{Name: "marketing_opt_in_level", DataType: schema.TypeString},
				{Name: "locale", DataType: schema.TypeString},
				{Name: "orders_count", DataType: schema.TypeInt64},
				{Name: "total_spent", DataType: schema.TypeFloat64},
				{Name: "currency", DataType: schema.TypeString},
				{Name: "default_address", DataType: schema.TypeJSON},
				{Name: "addresses", DataType: schema.TypeJSON},
				{Name: "email_marketing_consent", DataType: schema.TypeJSON},
				{Name: "sms_marketing_consent", DataType: schema.TypeJSON},
				{Name: "last_order_id", DataType: schema.TypeInt64},
				{Name: "last_order_name", DataType: schema.TypeString},
			},
			ExpectedRowCount: 2,
			Rows: []testutil.ExpectedRow{
				{
					ID: "9017191006296",
					Fields: map[string]any{
						"admin_graphql_api_id":   "gid://shopify/Customer/9017191006296",
						"email":                  "jane.doe@gongtest.com",
						"first_name":             "Jane",
						"last_name":              "Doe",
						"phone":                  nil,
						"created_at":             time.Date(2026, 2, 16, 5, 16, 59, 0, time.UTC),
						"state":                  "disabled",
						"note":                   nil,
						"tags":                   "test, vip",
						"tax_exempt":             false,
						"verified_email":         true,
						"multipass_identifier":   nil,
						"accepts_marketing":      false,
						"marketing_opt_in_level": "SINGLE_OPT_IN",
						"locale":                 "en",
						"total_spent":            float64(15.0),
						"currency":               "TRY",
						"last_order_id":          int64(6540423856216),
						"last_order_name":        "#1002",
					},
				},
				{
					ID: "9017193955416",
					Fields: map[string]any{
						"admin_graphql_api_id":   "gid://shopify/Customer/9017193955416",
						"email":                  "test.customer@gongtest.com",
						"first_name":             "Test",
						"last_name":              "Customer",
						"phone":                  nil,
						"created_at":             time.Date(2026, 2, 16, 5, 18, 2, 0, time.UTC),
						"state":                  "disabled",
						"note":                   nil,
						"tags":                   "integration, test",
						"tax_exempt":             false,
						"verified_email":         true,
						"multipass_identifier":   nil,
						"accepts_marketing":      false,
						"marketing_opt_in_level": "SINGLE_OPT_IN",
						"locale":                 "en",
						"total_spent":            float64(50.0),
						"currency":               "TRY",
						"last_order_id":          int64(6540423561304),
						"last_order_name":        "#1001",
					},
				},
			},
		},
		{
			SourceTable: "orders",
			DestTable:   "main.shopify_orders",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "admin_graphql_api_id", DataType: schema.TypeString},
				{Name: "app_id", DataType: schema.TypeInt64},
				{Name: "billing_address", DataType: schema.TypeJSON},
				{Name: "browser_ip", DataType: schema.TypeString},
				{Name: "buyer_accepts_marketing", DataType: schema.TypeBoolean},
				{Name: "cancel_reason", DataType: schema.TypeString},
				{Name: "cancelled_at", DataType: schema.TypeTimestampTZ},
				{Name: "cart_token", DataType: schema.TypeString},
				{Name: "checkout_token", DataType: schema.TypeString},
				{Name: "client_details", DataType: schema.TypeJSON},
				{Name: "closed_at", DataType: schema.TypeTimestampTZ},
				{Name: "company", DataType: schema.TypeJSON},
				{Name: "confirmation_number", DataType: schema.TypeString},
				{Name: "confirmed", DataType: schema.TypeBoolean},
				{Name: "contact_email", DataType: schema.TypeString},
				{Name: "created_at", DataType: schema.TypeTimestampTZ},
				{Name: "currency", DataType: schema.TypeString},
				{Name: "current_subtotal_price", DataType: schema.TypeFloat64},
				{Name: "current_subtotal_price_set", DataType: schema.TypeJSON},
				{Name: "current_total_additional_fees_set", DataType: schema.TypeJSON},
				{Name: "current_total_discounts", DataType: schema.TypeFloat64},
				{Name: "current_total_discounts_set", DataType: schema.TypeJSON},
				{Name: "current_total_duties_set", DataType: schema.TypeJSON},
				{Name: "current_total_price", DataType: schema.TypeFloat64},
				{Name: "current_total_price_set", DataType: schema.TypeJSON},
				{Name: "current_total_tax", DataType: schema.TypeFloat64},
				{Name: "current_total_tax_set", DataType: schema.TypeJSON},
				{Name: "customer", DataType: schema.TypeJSON},
				{Name: "customer_locale", DataType: schema.TypeString},
				{Name: "discount_applications", DataType: schema.TypeJSON},
				{Name: "discount_codes", DataType: schema.TypeJSON},
				{Name: "email", DataType: schema.TypeString},
				{Name: "estimated_taxes", DataType: schema.TypeBoolean},
				{Name: "financial_status", DataType: schema.TypeString},
				{Name: "fulfillment_status", DataType: schema.TypeString},
				{Name: "fulfillments", DataType: schema.TypeJSON},
				{Name: "gateway", DataType: schema.TypeString},
				{Name: "landing_site", DataType: schema.TypeString},
				{Name: "line_items", DataType: schema.TypeJSON},
				{Name: "location_id", DataType: schema.TypeInt64},
				{Name: "merchant_of_record_app_id", DataType: schema.TypeInt64},
				{Name: "name", DataType: schema.TypeString},
				{Name: "note", DataType: schema.TypeString},
				{Name: "note_attributes", DataType: schema.TypeJSON},
				{Name: "number", DataType: schema.TypeInt64},
				{Name: "order_number", DataType: schema.TypeInt64},
				{Name: "order_status_url", DataType: schema.TypeString},
				{Name: "original_total_additional_fees_set", DataType: schema.TypeJSON},
				{Name: "original_total_duties_set", DataType: schema.TypeJSON},
				{Name: "payment_gateway_names", DataType: schema.TypeJSON},
				{Name: "payment_terms", DataType: schema.TypeJSON},
				{Name: "phone", DataType: schema.TypeString},
				{Name: "po_number", DataType: schema.TypeString},
				{Name: "presentment_currency", DataType: schema.TypeString},
				{Name: "processed_at", DataType: schema.TypeTimestampTZ},
				{Name: "referring_site", DataType: schema.TypeString},
				{Name: "refunds", DataType: schema.TypeJSON},
				{Name: "shipping_address", DataType: schema.TypeJSON},
				{Name: "shipping_lines", DataType: schema.TypeJSON},
				{Name: "source_identifier", DataType: schema.TypeString},
				{Name: "source_name", DataType: schema.TypeString},
				{Name: "source_url", DataType: schema.TypeString},
				{Name: "subtotal_price", DataType: schema.TypeFloat64},
				{Name: "subtotal_price_set", DataType: schema.TypeJSON},
				{Name: "tags", DataType: schema.TypeString},
				{Name: "tax_exempt", DataType: schema.TypeBoolean},
				{Name: "tax_lines", DataType: schema.TypeJSON},
				{Name: "taxes_included", DataType: schema.TypeBoolean},
				{Name: "test", DataType: schema.TypeBoolean},
				{Name: "token", DataType: schema.TypeString},
				{Name: "total_discounts", DataType: schema.TypeFloat64},
				{Name: "total_discounts_set", DataType: schema.TypeJSON},
				{Name: "total_line_items_price", DataType: schema.TypeFloat64},
				{Name: "total_line_items_price_set", DataType: schema.TypeJSON},
				{Name: "total_outstanding", DataType: schema.TypeFloat64},
				{Name: "total_price", DataType: schema.TypeFloat64},
				{Name: "total_price_set", DataType: schema.TypeJSON},
				{Name: "total_shipping_price_set", DataType: schema.TypeJSON},
				{Name: "total_tax", DataType: schema.TypeFloat64},
				{Name: "total_tax_set", DataType: schema.TypeJSON},
				{Name: "total_tip_received", DataType: schema.TypeFloat64},
				{Name: "total_weight", DataType: schema.TypeFloat64},
				{Name: "updated_at", DataType: schema.TypeTimestampTZ},
				{Name: "user_id", DataType: schema.TypeInt64},
				{Name: "duties_included", DataType: schema.TypeBoolean},
				{Name: "merchant_business_entity_id", DataType: schema.TypeString},
				{Name: "total_cash_rounding_payment_adjustment_set", DataType: schema.TypeJSON},
				{Name: "total_cash_rounding_refund_adjustment_set", DataType: schema.TypeJSON},
			},
			ExpectedRowCount: 2,
			Rows: []testutil.ExpectedRow{
				{
					ID: "6540423561304",
					Fields: map[string]any{
						"admin_graphql_api_id":    "gid://shopify/Order/6540423561304",
						"name":                    "#1001",
						"order_number":            int64(1001),
						"email":                   "test.customer@gongtest.com",
						"phone":                   nil,
						"contact_email":           "test.customer@gongtest.com",
						"created_at":              time.Date(2026, 2, 16, 5, 18, 20, 0, time.UTC),
						"processed_at":            time.Date(2026, 2, 16, 5, 18, 20, 0, time.UTC),
						"closed_at":               nil,
						"cancelled_at":            nil,
						"cancel_reason":           nil,
						"currency":                "TRY",
						"financial_status":        "paid",
						"fulfillment_status":      "unfulfilled",
						"confirmed":               true,
						"test":                    false,
						"buyer_accepts_marketing": false,
						"taxes_included":          false,
						"tax_exempt":              false,
						"note":                    nil,
						"tags":                    "integration, test",
						"total_weight":            float64(0.0),
						"subtotal_price":          float64(50.0),
						"total_price":             float64(50.0),
						"total_tax":               float64(0.0),
						"total_discounts":         float64(0.0),
						"current_total_price":     float64(50.0),
						"current_subtotal_price":  float64(50.0),
						"current_total_tax":       float64(0.0),
						"current_total_discounts": float64(0.0),
						"landing_site":            nil,
						"referring_site":          nil,
						"source_identifier":       nil,
						"source_url":              nil,
						"customer_locale":         nil,
						"app_id":                  int64(323148152833),
						"cart_token":              nil,
						"checkout_token":          nil,
						"token":                   nil,
						"gateway":                 nil,
						"total_outstanding":       float64(50.0),
						"total_tip_received":      float64(0.0),
					},
				},
				{
					ID: "6540423856216",
					Fields: map[string]any{
						"admin_graphql_api_id":    "gid://shopify/Order/6540423856216",
						"name":                    "#1002",
						"order_number":            int64(1002),
						"email":                   "jane.doe@gongtest.com",
						"phone":                   nil,
						"contact_email":           "jane.doe@gongtest.com",
						"created_at":              time.Date(2026, 2, 16, 5, 18, 38, 0, time.UTC),
						"processed_at":            time.Date(2026, 2, 16, 5, 18, 38, 0, time.UTC),
						"closed_at":               nil,
						"cancelled_at":            nil,
						"cancel_reason":           nil,
						"currency":                "TRY",
						"financial_status":        "paid",
						"fulfillment_status":      "unfulfilled",
						"confirmed":               true,
						"test":                    false,
						"buyer_accepts_marketing": false,
						"taxes_included":          false,
						"tax_exempt":              false,
						"note":                    nil,
						"tags":                    "test",
						"total_weight":            float64(0.0),
						"subtotal_price":          float64(15.0),
						"total_price":             float64(15.0),
						"total_tax":               float64(0.0),
						"total_discounts":         float64(0.0),
						"current_total_price":     float64(15.0),
						"current_subtotal_price":  float64(15.0),
						"current_total_tax":       float64(0.0),
						"current_total_discounts": float64(0.0),
						"landing_site":            nil,
						"referring_site":          nil,
						"source_identifier":       nil,
						"source_url":              nil,
						"customer_locale":         nil,
						"app_id":                  int64(323148152833),
						"cart_token":              nil,
						"checkout_token":          nil,
						"token":                   nil,
						"gateway":                 nil,
						"total_outstanding":       float64(15.0),
						"total_tip_received":      float64(0.0),
					},
				},
			},
		},
		{
			SourceTable: "discounts",
			DestTable:   "main.shopify_discounts",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "discount", DataType: schema.TypeJSON},
				{Name: "metafields_first250", DataType: schema.TypeJSON},
			},
			ExpectedRowCount: 1,
		},
		{
			SourceTable: "inventory_items",
			DestTable:   "main.shopify_inventory_items",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeString},
				{Name: "created_at", DataType: schema.TypeTimestampTZ},
				{Name: "duplicate_sku_count", DataType: schema.TypeInt64},
				{Name: "legacy_resource_id", DataType: schema.TypeString},
				{Name: "measurement", DataType: schema.TypeJSON},
				{Name: "requires_shipping", DataType: schema.TypeBoolean},
				{Name: "sku", DataType: schema.TypeString},
				{Name: "tracked", DataType: schema.TypeBoolean},
				{Name: "tracked_editable", DataType: schema.TypeJSON},
				{Name: "updated_at", DataType: schema.TypeTimestampTZ},
				{Name: "inventory_levels", DataType: schema.TypeJSON},
				{Name: "variant", DataType: schema.TypeJSON},
			},
			ExpectedRowCount: 4,
			Rows: []testutil.ExpectedRow{
				{
					ID: "gid://shopify/InventoryItem/45868329893976",
					Fields: map[string]any{
						"sku":               "GONG-MUG-01",
						"tracked":           true,
						"requires_shipping": true,
					},
				},
				{
					ID: "gid://shopify/InventoryItem/45868331532376",
					Fields: map[string]any{
						"sku":               "GONG-TSHIRT-S",
						"tracked":           true,
						"requires_shipping": true,
					},
				},
				{
					ID: "gid://shopify/InventoryItem/45868331565144",
					Fields: map[string]any{
						"sku":               "GONG-TSHIRT-M",
						"tracked":           true,
						"requires_shipping": true,
					},
				},
				{
					ID: "gid://shopify/InventoryItem/45868331597912",
					Fields: map[string]any{
						"sku":               "GONG-TSHIRT-L",
						"tracked":           true,
						"requires_shipping": true,
					},
				},
			},
		},
		{
			SourceTable: "events",
			DestTable:   "main.shopify_events",
			KeyColumn:   "id",
			ExpectedSchema: []schema.Column{
				{Name: "id", DataType: schema.TypeInt64},
				{Name: "subject_id", DataType: schema.TypeInt64},
				{Name: "created_at", DataType: schema.TypeTimestampTZ},
				{Name: "subject_type", DataType: schema.TypeString},
				{Name: "verb", DataType: schema.TypeString},
				{Name: "arguments", DataType: schema.TypeJSON},
				{Name: "message", DataType: schema.TypeString},
				{Name: "description", DataType: schema.TypeString},
			},
			Rows: []testutil.ExpectedRow{
				{
					ID: "145186209529944",
					Fields: map[string]any{
						"created_at":   time.Date(2026, 2, 14, 12, 9, 45, 0, time.UTC),
						"subject_type": "Blog",
						"subject_id":   int64(93463969880),
						"verb":         "create",
					},
				},
				{
					ID: "145264925442136",
					Fields: map[string]any{
						"created_at":   time.Date(2026, 2, 16, 5, 16, 53, 0, time.UTC),
						"subject_type": "Product",
						"subject_id":   int64(8671508725848),
						"verb":         "create",
					},
				},
				{
					ID: "145264958570584",
					Fields: map[string]any{
						"created_at":   time.Date(2026, 2, 16, 5, 18, 20, 0, time.UTC),
						"subject_type": "Order",
						"subject_id":   int64(6540423561304),
						"verb":         "placed",
					},
				},
				{
					ID: "145264965845080",
					Fields: map[string]any{
						"created_at":   time.Date(2026, 2, 16, 5, 18, 38, 0, time.UTC),
						"subject_type": "Order",
						"subject_id":   int64(6540423856216),
						"verb":         "placed",
					},
				},
			},
		},
	}

	for _, exp := range expectations {
		t.Run(exp.SourceTable, func(t *testing.T) {
			testutil.RunPipeline(t, ctx, sourceURI, destURI, exp)
			testutil.Check(t, destURI, exp)
		})
	}
}
